# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pajak.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(50, 81, 301, 130))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditHarga = QtWidgets.QLineEdit(self.widget)
        self.lineEditHarga.setObjectName("lineEditHarga")
        self.gridLayout.addWidget(self.lineEditHarga, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditPajak = QtWidgets.QComboBox(self.widget)
        self.lineEditPajak.setObjectName("lineEditPajak")
        self.lineEditPajak.addItem("")
        self.lineEditPajak.addItem("")
        self.lineEditPajak.addItem("")
        self.gridLayout.addWidget(self.lineEditPajak, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.lineEditPajak.clearEditText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PERHITUNGAN PAJAK"))
        self.label_2.setText(_translate("Dialog", "HARGA"))
        self.label_3.setText(_translate("Dialog", "Pajak"))
        self.lineEditPajak.setItemText(0, _translate("Dialog", "5%"))
        self.lineEditPajak.setItemText(1, _translate("Dialog", "10%"))
        self.lineEditPajak.setItemText(2, _translate("Dialog", "15%"))
        self.pushButton.setText(_translate("Dialog", "Hitung Pajak"))
        self.label_4.setText(_translate("Dialog", "Total Harga Besaran Pajak Anda"))
