# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sevapbo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1047, 823)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 130, 351, 521))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabelcatatan = QtWidgets.QTableWidget(self.layoutWidget)
        self.tabelcatatan.setObjectName("tabelcatatan")
        self.tabelcatatan.setColumnCount(0)
        self.tabelcatatan.setRowCount(0)
        self.gridLayout.addWidget(self.tabelcatatan, 3, 0, 1, 2)
        self.tambahcatatan = QtWidgets.QPushButton(self.layoutWidget)
        self.tambahcatatan.setObjectName("tambahcatatan")
        self.gridLayout.addWidget(self.tambahcatatan, 4, 1, 1, 1)
        self.inputteks = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputteks.setObjectName("inputteks")
        self.gridLayout.addWidget(self.inputteks, 2, 0, 1, 2)
        self.pencaricatatan = QtWidgets.QPushButton(self.layoutWidget)
        self.pencaricatatan.setObjectName("pencaricatatan")
        self.gridLayout.addWidget(self.pencaricatatan, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.hapuscatatanyangdipilih = QtWidgets.QPushButton(self.layoutWidget)
        self.hapuscatatanyangdipilih.setObjectName("hapuscatatanyangdipilih")
        self.gridLayout.addWidget(self.hapuscatatanyangdipilih, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.hapuscatatanyangdipilih.clicked['bool'].connect(self.tabelcatatan.clearSelection) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tambahcatatan.setText(_translate("Dialog", "Tambah"))
        self.pencaricatatan.setText(_translate("Dialog", "Cari"))
        self.label.setText(_translate("Dialog", "SEMUA CATATAN"))
        self.hapuscatatanyangdipilih.setText(_translate("Dialog", "Hapus"))
